export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';

export const PUSH_NEW_ROUTE = 'PUSH_NEW_ROUTE';
export const REPLACE_ROUTE = 'REPLACE_ROUTE';
export const REPLACE_OR_PUSH_ROUTE = 'REPLACE_OR_PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';
export const POP_TO_ROUTE = 'POP_TO_ROUTE';

export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const ADD_STORY = 'ADD_STORY';
export const REQUEST_STORIES = 'REQUEST_STORIES';
export const RECEIVE_STORIES = 'RECEIVE_STORIES';
export const BUY_STORY = 'BUY_STORY';


export const INVALIDATE_PURPOSE = 'INVALIDATE_PURPOSE';
export const SEE_STORY = 'SEE_STORY';
export const SET_STORIES_RESOURCE = 'SET_STORIES_RESOURCE';


export const SET_USER_TOKEN = 'SET_USER_TOKEN';


/*
 * другие константы
 */
export const PossiblePurposes = {
    SHOP: 'SHOP',
    USER: 'USER'
};

//Bluetooth

export const ENABLE_BLUETOOTH = 'ENABLE_BLUETOOTH';
export const DISABLE_BLUETOOTH = 'DISABLE_BLUETOOTH';

export const CONNECT_BLUETOOTH = 'CONNECT_BLUETOOTH';
export const UNCONNECT_BLUETOOTH = 'UNCONNECT_BLUETOOTH';
export const ISCONNECTED_BLUETOOTH = 'ISCONNECTED_BLUETOOTH';

export const SEARCH_BEARS = 'SEARCH_BEARS';

//Bear
export const SET_BEAR_STORIES = 'SET_BEAR_STORIES';
export const SET_CONNECTED_BEAR_NAME = 'SET_CONNECTED_BEAR_NAME';
export const UPLOAD_STORY = 'UPLOAD_STORY';
export const DELETE_STORY = 'DELETE_STORY';
export const PLAY_STORY = 'PLAY_STORY';
export const PAUSE_STORY = 'PAUSE_STORY';